
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N18"
stages:
  Build:
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Malware Scan:
    malwareExecuteScan: true
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "50843294trial"
    cfSpace: "dev"
    cfCredentialsId: "cfdeploytest"
    deployType: "standard"
    tmsUpload: true
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "qa"
    credentialsId: "tmshso-key"
    mtaVersion: "*"               #Defines the version of the MTA for which the MTA extension descriptor will be used. You can use an asterisk (*)
    verbose: true